### ISSUE TITLE
Aluminum/Bauxite not generating

### ISSUE THREAD

**Issue by Murdoc14** [Murdoc14/1kB-MagiTech#16]
The ore blocks are valid and JEI shows proper distribution,

**Comment by TokkenGmr** [comment]
As we discussed i think this is a simple config change. Easy enough.

**Comment by Murdoc14** [comment]
Fixed via  [83b0645](https://github.com/Murdoc14/1kB-MagiTech/commit/83b0645a7180866f3ab24d7cf6be76e256fc8f0c)
