### ISSUE TITLE
Iron plates cannot be crafted in smelter

### ISSUE THREAD

**Issue by TokkenGmr** [Murdoc14/1kB-MagiTech#18]
iron plates cannot be crafted in smelter like other plates

**Comment by Murdoc14** [comment]
Temporarily bypassed but not fixed

**Comment by Murdoc14** [comment]
Fixed Via [622cf29](https://github.com/Murdoc14/1kB-MagiTech/commit/622cf2956c484ad06928c5c7f11ed5a6908bec17)
