### ISSUE TITLE
Harvestcraft Gardens do not have drops.

### ISSUE THREAD

**Issue by Murdoc14** [Murdoc14/1kB-MagiTech#39]
Registering drops for shadedGarden.
Unable to find item harvestcraft:whitemushroomItem to add to this garden.
Unable to find item harvestcraft:blackberryItem to add to this garden.
Unable to find item harvestcraft:zucchiniItem to add to this garden.
Unable to find item harvestcraft:radishItem to add to this garden.
Unable to find item harvestcraft:rhubarbItem to add to this garden.
Unable to find item harvestcraft:tealeafItem to add to this garden.
Unable to find item harvestcraft:garlicItem to add to this garden.
Unable to find item harvestcraft:sweetpotatoItem to add to this garden.
Unable to find item harvestcraft:turnipItem to add to this garden.
Unable to find item harvestcraft:spiceleafItem to add to this garden.
Unable to find item harvestcraft:beanItem to add to this garden.
Unable to find item harvestcraft:leekItem to add to this garden.
Unable to find item harvestcraft:scallionItem to add to this garden.
Unable to find item harvestcraft:tomatoItem to add to this garden.
Unable to find item harvestcraft:cottonItem to add to this garden.

Registering drops for tropicalGarden.
Unable to find item harvestcraft:grapeItem to add to this garden.
Unable to find item harvestcraft:pineappleItem to add to this garden.
Unable to find item harvestcraft:kiwiItem to add to this garden.
Unable to find item harvestcraft:sesameseedsItem to add to this garden.
Unable to find item harvestcraft:curryleafItem to add to this garden.
Unable to find item harvestcraft:bambooshootItem to add to this garden.
Unable to find item harvestcraft:cantaloupeItem to add to this garden.
Unable to find item harvestcraft:gingerItem to add to this garden.
Unable to find item harvestcraft:coffeebeanItem to add to this garden.
Unable to find item harvestcraft:soybeanItem to add to this garden.
Unable to find item harvestcraft:eggplantItem to add to this garden.
Unable to find item harvestcraft:cottonItem to add to this garden.

Registering drops for windyGarden.
Unable to find item harvestcraft:strawberryItem to add to this garden.
Unable to find item harvestcraft:barleyItem to add to this garden.
Unable to find item harvestcraft:cornItem to add to this garden.
Unable to find item harvestcraft:cucumberItem to add to this garden.
Unable to find item harvestcraft:wintersquashItem to add to this garden.
Unable to find item harvestcraft:mustardseedsItem to add to this garden.
Unable to find item harvestcraft:onionItem to add to this garden.
Unable to find item harvestcraft:parsnipItem to add to this garden.
Unable to find item harvestcraft:peanutItem to add to this garden.
Unable to find item harvestcraft:lettuceItem to add to this garden.
Unable to find item harvestcraft:artichokeItem to add to this garden.
Unable to find item harvestcraft:bellpepperItem to add to this garden.
Unable to find item harvestcraft:chilipepperItem to add to this garden.
Unable to find item harvestcraft:cottonItem to add to this garden.

Registering drops for frostGarden.
Unable to find item harvestcraft:raspberryItem to add to this garden.
Unable to find item harvestcraft:oatsItem to add to this garden.
Unable to find item harvestcraft:ryeItem to add to this garden.
Unable to find item harvestcraft:celeryItem to add to this garden.
Unable to find item harvestcraft:peasItem to add to this garden.
Unable to find item harvestcraft:beetItem to add to this garden.
Unable to find item harvestcraft:rutabagaItem to add to this garden.
Unable to find item harvestcraft:broccoliItem to add to this garden.
Unable to find item harvestcraft:cauliflowerItem to add to this garden.
Unable to find item harvestcraft:cabbageItem to add to this garden.
Unable to find item harvestcraft:spinachItem to add to this garden.
Unable to find item harvestcraft:cottonItem to add to this garden.

Registering drops for aridGarden.
Unable to find item harvestcraft:cactusfruitItem to add to this garden.

Registering drops for soggyGarden.
Unable to find item harvestcraft:brusselsproutItem to add to this garden.
Unable to find item harvestcraft:spiceleafItem to add to this garden.
Unable to find item harvestcraft:blueberryItem to add to this garden.
Unable to find item harvestcraft:asparagusItem to add to this garden.
Unable to find item harvestcraft:cranberryItem to add to this garden.
Unable to find item harvestcraft:riceItem to add to this garden.
Unable to find item harvestcraft:seaweedItem to add to this garden.
Unable to find item harvestcraft:waterchestnutItem to add to this garden.
Unable to find item harvestcraft:okraItem to add to this garden.
Unable to find item harvestcraft:cottonItem to add to this garden.

**Comment by TokkenGmr** [comment]
Need to regenerate the config file to fix this

**Comment by Murdoc14** [comment]
Fixed.  Capitalization issue on Item names.
